name: Pelorus Exporter Build

on:
  push:
    branches:
      - test_build_image
    paths:
      - 'exporters/**'
      - 'charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml'
      - 'charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml'
      - '.github/workflows/build-pelorus.yml'

env:
  builder_image: 'registry.access.redhat.com/ubi8/python-39'
  imageregistry: 'quay.io'
  # default 'pelorus'
  imagenamespace: ${{ secrets.QUAY_IMAGE_NAMESPACE }}
  latesttag: latest
  s2i_log_level: 2

jobs:
  build-committime:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build committime
        uses: "./.github/workflow_templates/build_push_exporters"
        with:
          image: 'pelorus-committime-exporter'
          builder_image: ${{ env.builder_image }}
          latest_tag: ${{ env.latesttag }}
          sha_tag: ${{ github.sha }}
          s2i_log_level: ${{ env.s2i_log_level }}

      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: 'pelorus-committime-exporter'
          tags: ${{ env.latesttag }} ${{ github.sha }} ${{ env.VERSION }}
          registry: ${{ env.imageregistry }}/${{ env.imagenamespace }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
