name: Pelorus Exporter Build

on:
  push:
    branches:
      - test_build
    paths:
      - exporters/
      - charts/pelorus/charts/exporters/templates/_buildconfig.yaml
      - .github/workflows/build-pelorus.yaml

env:
  runs_on_image: 'ubuntu-20.04'
  builder_image: 'registry.access.redhat.com/ubi8/python-39'
  imageregistry: 'quay.io'
  # default 'pelorus'
  imagenamespace: ${{ secrets.QUAY_IMAGE_NAMESPACE }}
  latesttag: latest
  s2i_log_level: 2

jobs:
  build-committime:
    runs-on: ${{ env.runs_on_image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup S2i and Build container image
      - name: Setup and Build
        id: build-exporter
        uses: redhat-actions/s2i-build@v2
        with:
          image: 'committime-exporter'
          path_context: 'exporters'
          builder_image: ${{ env.builder_image }}
          tags: ${{ env.latesttag }} ${{ github.sha }}
          log_level: ${{ env.s2i_log_level }}

      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-exporter.outputs.image }}
          tags: ${{ steps.build-exporter.outputs.tags }}
          registry: ${{ env.imageregistry }}/${{ env.imagenamespace }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}


  build-deploytime:
    runs-on: ${{ env.runs_on_image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup S2i and Build container image
      - name: Setup and Build
        id: build-exporter
        uses: redhat-actions/s2i-build@v2
        with:
          image: 'committime-exporter'
          path_context: 'exporters'
          builder_image: ${{ env.builder_image }}
          tags: ${{ env.latesttag }} ${{ github.sha }}
          log_level: ${{ env.s2i_log_level }}


      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-exporter.outputs.image }}
          tags: ${{ steps.build-exporter.outputs.tags }}
          registry: ${{ env.imageregistry }}/${{ env.imagenamespace }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}


  build-failure:
    runs-on: ${{ env.runs_on_image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup S2i and Build container image
      - name: Setup and Build
        id: build-exporter
        uses: redhat-actions/s2i-build@v2
        with:
          image: 'committime-exporter'
          path_context: 'exporters'
          builder_image: ${{ env.builder_image }}
          tags: ${{ env.latesttag }} ${{ github.sha }}
          log_level: ${{ env.s2i_log_level }}


      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-exporter.outputs.image }}
          tags: ${{ steps.build-exporter.outputs.tags }}
          registry: ${{ env.imageregistry }}/${{ env.imagenamespace }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
