name: Pelorus Exporter Build

on:
  push:
    branches:
      - test_build_image
    paths:
      - 'exporters/**'
      - 'charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml'
      - 'charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml'
      - '.github/workflows/build-pelorus.yml'

env:
  builder_image: 'registry.access.redhat.com/ubi8/python-39'
  imageregistry: 'quay.io'
  # default 'pelorus'
  imagenamespace: ${{ secrets.QUAY_IMAGE_NAMESPACE }}
  latesttag: latest
  s2i_log_level: 2

jobs:
  build-committime:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build committime
        uses: "./.github/workflow_templates/build_push_exporters"
        with:
          exporter_type: committime

      # Setup S2i and Build container image
      - name: Setup and Build
        id: build-exporter
        uses: redhat-actions/s2i-build@v2
        with:
          image: 'pelorus-${{ inputs.version }}-exporter'
          path_context: 'exporters'
          builder_image: ${{ env.builder_image }}
          tags: ${{ env.latesttag }} ${{ github.sha }}
          log_level: ${{ env.s2i_log_level }}

      - name: Tag exporter image with additional version tag
        run: |
          docker tag ${{ steps.build-exporter.outputs.image }}:${{ github.sha }} ${{ steps.build-exporter.outputs.image }}:${{ env.VERSION }}

      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-exporter.outputs.image }}
          tags: ${{ steps.build-exporter.outputs.tags }} ${{ env.VERSION }}
          registry: ${{ env.imageregistry }}/${{ env.imagenamespace }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
